name: 'Release'

on:
  # push:
  #   branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          VERSION=v$(grep 'versionName ' app/build.gradle | awk '{print $2}' | sed 's|\"||g; s|\r$||g')
          FILENAME=delta-$VERSION
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create changelog
        run: |
          cat << EOF > changelog.md
          $(grep '^ *<item>' app/src/main/res/values/changelog.xml | sed -r 's|<[^>]*>(]]>)?||g; s|^ *|- |g')
          EOF

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up License Key
        run: echo LICENSE_KEY="${{ secrets.LICENSE_KEY }}" > local.properties

      - name: Build AAB
        run: bash gradlew bundleRelease

      - name: Build APK
        run: bash gradlew assembleRelease

      - name: Move AAB and APK
        run: |
          mkdir -v build && cd $_
          mv -v ../app/build/outputs/bundle/release/*.aab delta.aab
          mv -v ../app/build/outputs/apk/release/*.apk delta.apk

      - name: Sign AAB and APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}

      - name: Rename AAB and APK
        run: |
          cd build
          mv -v delta.aab ../${{ env.FILENAME }}.aab
          mv -v delta-signed.apk ../${{ env.FILENAME }}.apk

      - name: Upload APK in artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}
          path: ${{ env.FILENAME }}.apk
          retention-days: 30

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}.apk
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body_path: changelog.md

      ### uncomment later
      # - name: Upload to Play Store
      #   uses: r0adkll/upload-google-play@v1
      #   continue-on-error: true
      #   with:
      #     serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #     packageName: website.leifs.delta
      #     releaseFiles: ${{ env.FILENAME }}.aab
      #     track: production
      #     mappingFile: app/build/outputs/mapping/release/mapping.txt
